package universidadgrupo32;

import javax.swing.JOptionPane;
import universidadgrupo32accesoDatos.MateriaData;
import universidadgrupo32entidades.Materia;

public class GestionDeMaterias extends javax.swing.JInternalFrame {
    
    public GestionDeMaterias() {
        initComponents();
        jBguardarMat.setEnabled(false);
        jBeliminarMat.setEnabled(false);
        jTnombreMat.setEnabled(false);
        jTaño.setEnabled(false);
        jRestadoMat.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBnuevoMat = new javax.swing.JButton();
        jBeliminarMat = new javax.swing.JButton();
        jBguardarMat = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jBbuscarMat = new javax.swing.JButton();
        jTidMateria = new javax.swing.JTextField();
        jTnombreMat = new javax.swing.JTextField();
        jTaño = new javax.swing.JTextField();
        jRestadoMat = new javax.swing.JRadioButton();

        setTitle("Materias");

        jLabel1.setText("Materia");

        jLabel2.setText("Codigo");

        jLabel3.setText("Nombre");

        jLabel4.setText("Año");

        jLabel5.setText("Estado");

        jBnuevoMat.setText("Nuevo");
        jBnuevoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoMatActionPerformed(evt);
            }
        });

        jBeliminarMat.setText("Eliminar");
        jBeliminarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarMatActionPerformed(evt);
            }
        });

        jBguardarMat.setText("Guardar");
        jBguardarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarMatActionPerformed(evt);
            }
        });

        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        jBbuscarMat.setText("Buscar");
        jBbuscarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarMatActionPerformed(evt);
            }
        });

        jTidMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTidMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBbuscarMat))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTnombreMat, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTaño, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(74, 74, 74))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRestadoMat)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBnuevoMat)
                        .addGap(13, 13, 13)
                        .addComponent(jBeliminarMat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBguardarMat)
                        .addGap(18, 18, 18)
                        .addComponent(jBsalir)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jBbuscarMat)
                    .addComponent(jTidMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTnombreMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRestadoMat))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnuevoMat)
                    .addComponent(jBeliminarMat)
                    .addComponent(jBguardarMat)
                    .addComponent(jBsalir))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBguardarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarMatActionPerformed
        // TODO add your handling code here:
        try {
            int anio = Integer.parseInt(jTaño.getText());
            Materia materia = new Materia(jTnombreMat.getText(), anio, true);
            MateriaData md = new MateriaData();
            if (!"".equals(jTnombreMat.getText())) {
                if (md.buscarMateriaNombreAno(jTnombreMat.getText(), anio) == false) {
                    md.guardarMateria(materia);
                    jTnombreMat.setText("");
                    jTaño.setText("");
                    jBguardarMat.setEnabled(false);
                    jBeliminarMat.setEnabled(false);
                    jTnombreMat.setEnabled(false);
                    jTaño.setEnabled(false);
                    jRestadoMat.setEnabled(false);
                    jTidMateria.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(this, "LA MATERIA YA SE ENCUENTRA INGRESADA");
                    jTnombreMat.setText("");
                    jTaño.setText("");
                    jBguardarMat.setEnabled(false);
                    jBeliminarMat.setEnabled(false);
                    jTnombreMat.setEnabled(false);
                    jTaño.setEnabled(false);
                    jRestadoMat.setEnabled(false);
                    jTidMateria.setEnabled(true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "NOMBRE DE MATERIA VACIO");
                jTnombreMat.setText("");
                jTaño.setText("");
            }
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "EL AÑO INGRESADO NO CORRESPONDE A UN NUMERO VALIDO");
            jTaño.setText("");
        }
    }//GEN-LAST:event_jBguardarMatActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jTidMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidMateriaActionPerformed

    private void jBnuevoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoMatActionPerformed
        // TODO add your handling code here:
        jBguardarMat.setEnabled(true);
        jBeliminarMat.setEnabled(false);
        jTnombreMat.setEnabled(true);
        jTaño.setEnabled(true);
        jRestadoMat.setEnabled(false);
        jTidMateria.setEnabled(false);
        

    }//GEN-LAST:event_jBnuevoMatActionPerformed

    private void jBbuscarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarMatActionPerformed
        // TODO add your handling code here:
        Materia materia = new Materia();
        MateriaData md = new MateriaData();
        try {
            int id = Integer.parseInt(jTidMateria.getText());
            
            if (md != null) {
                materia = md.buscarMateriaID(id);
                jTnombreMat.setEnabled(true);
                jTaño.setEnabled(true);
                jRestadoMat.setEnabled(true);
                jBnuevoMat.setEnabled(false);
                jBguardarMat.setEnabled(false);
                jBeliminarMat.setEnabled(true);
                jTnombreMat.setText(materia.getNombre());
                jTaño.setText(materia.getAnio() + "");
                if (materia.isEstado()) {
                    jRestadoMat.setSelected(true);
                } else {
                    jRestadoMat.setSelected(false);
                }
            } else {
                JOptionPane.showMessageDialog(this, "NO EXISTE LA MATERIA");
            }
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "CODIGO NO ES UN NÚMERO VALIDO");
        }
    }//GEN-LAST:event_jBbuscarMatActionPerformed

    private void jBeliminarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarMatActionPerformed
        // TODO add your handling code here:
        Materia materia = new Materia();
        MateriaData md = new MateriaData();
        int id = Integer.parseInt(jTidMateria.getText());
        md.bajaMateria(id);
        jTidMateria.setText("");
        jTnombreMat.setText("");
        jTaño.setText("");
        jBnuevoMat.setEnabled(true);
        jBguardarMat.setEnabled(false);
        jBeliminarMat.setEnabled(false);
        jTnombreMat.setEnabled(false);
        jTaño.setEnabled(false);
        jRestadoMat.setEnabled(false);
    }//GEN-LAST:event_jBeliminarMatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscarMat;
    private javax.swing.JButton jBeliminarMat;
    private javax.swing.JButton jBguardarMat;
    private javax.swing.JButton jBnuevoMat;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRestadoMat;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTaño;
    private javax.swing.JTextField jTidMateria;
    private javax.swing.JTextField jTnombreMat;
    // End of variables declaration//GEN-END:variables
}
